Feature: Daily recap playbook is generated by the playbook_generation builder
  A daily_recap candidate enters Anvil through candidate_playbook_intake. The
  shipped playbook_generation builder is then driven through the engine until
  terminal completion, where it persists a generated daily_recap machine into a
  hermetic owner-home.

  Scenario: candidate intake drives the builder to generate and persist daily_recap
    Given a hearth seeded with the builder machine and an active parent track "20260606T0000_builder_parent_track"
    And the engine is started with that hearth
    And a .hearth file pointing to that directory while the running engine remains active
    And the MCP shim is started in that working directory with the running engine endpoint
    And the MCP session is initialized while the running engine remains active
    And a separate temp owner-home directory for MCP persist_playbook
    And the engine hearth playbooks entry count is recorded for MCP persist_playbook
    When a candidate_playbook_intake tools/call is sent with candidate fields and proposed states:
      | field          | value                                  | state        | role | intent                                                                                                                                                  | expected_output                                                                                         |
      | source         | lore-emitter                           |              |      |                                                                                                                                                         |                                                                                                         |
      | intent         | daily recap                            |              |      |                                                                                                                                                         |                                                                                                         |
      | at             | 2026-06-08T00:00:00Z                   |              |      |                                                                                                                                                         |                                                                                                         |
      | evidence       | lore:obs-1,git:commit-abc              |              |      |                                                                                                                                                         |                                                                                                         |
      | target_owner   | <mcp_persist_owner_home>               |              |      |                                                                                                                                                         |                                                                                                         |
      | parent_id      | 20260606T0000_builder_parent_track     |              |      |                                                                                                                                                         |                                                                                                         |
      | actor_name     | Daily-Recap-Builder-Intake-100000      |              |      |                                                                                                                                                         |                                                                                                         |
      | actor_type     | agent                                  |              |      |                                                                                                                                                         |                                                                                                         |
      | actor_model    | gpt-5-codex                            |              |      |                                                                                                                                                         |                                                                                                         |
      | actor_provider | openai                                 |              |      |                                                                                                                                                         |                                                                                                         |
      |                |                                        | gathering    | doer | Collect the day's raw material deduplicated (Lore observations by date, git commits across hearths+repos, completed track transitions, new decisions) into a structured day-events bundle. | A structured day-events bundle: the day's events as deduplicated structured evidence.                    |
      |                |                                        | synthesizing | doer | From the day-events bundle produce a recap narrative, findings, and business opportunities, each claim tracing to a gathered event.                      | Recap + findings + opportunities, each citing its source event.                                         |
      |                |                                        | reporting    | doer | Format an audience-appropriate team-ready report and deliver it.                                                                                        | The final report + delivery confirmation.                                                              |
    And the intake builder is driven to completed through the MCP shim
    Then the complete response new_state is "completed"
    And the driven playbook_generation builder emitted non-degenerate step measurements for each builder step
    And a machine.yaml exists at "playbooks/daily_recap/machine.yaml" under the MCP persist owner-home
    And the persisted daily_recap generated playbook is loader-valid with three measured diamonds and no hooks
    And a fresh registry from the MCP persist owner-home resolves kind "daily_recap"
    And the engine hearth playbooks entry count is unchanged for MCP persist_playbook
